### ISSUE TITLE
Add more phone compatability

### ISSUE THREAD

**Issue by BradleyCai** [ammongit/ucr-class-map#13]
Popovers should be full width or they should be replaced with something more mobile friendly.
They currently look like this:

![image](https://cloud.githubusercontent.com/assets/7998948/11072340/3ae46bc6-879a-11e5-9d18-4fd8422423af.png)

Also, the calendar doesn't fit in the website and pushes the width out.

**Comment by emmiegit** [comment]
Obsolete.
