### ISSUE TITLE
Add building locations

### ISSUE THREAD

**Issue by BradleyCai** [ammongit/ucr-class-map#17]
Building locations will be linked in the popover. The in page map is not planned for this issue.

**Comment by ammongit** [comment]
Will this issue add a map?

**Comment by BradleyCai** [comment]
Buildings should be stored in a json. Each building abbreviation will have a corresponding building location link at http://campusmap.ucr.edu/imap/index.html

**Comment by emmiegit** [comment]
Instead of creating a JSON, we can just enter the building directly.
e.g.: `http://campusmap.ucr.edu/imap/index.html?loc=%s` where `%s` is replaced with the building name, say `BRNHL`.
