### ISSUE TITLE
Licensing and credits for dependencies

### ISSUE THREAD

**Issue by emmiegit** [ammongit/ucr-class-map#20]
Check all dependencies we're using, and list the license for each dependency. For example, the MIT License requires that the license be provided with the software that makes use of the dependency.

**Comment by BradleyCai** [comment]
Each dependency's license has been listed inside of it's respective js file as a comment. 

Each dependency's requirements appears to have been met.

**Comment by emmiegit** [comment]
I'll add a segment to our `README.md` that notes what you just said.
