### ISSUE TITLE
Website is not fully functional on Safari on Mac

### ISSUE THREAD

**Issue by BradleyCai** [ammongit/ucr-class-map#35]
Popovers do not seem to work.

Further testing must be done on safari in order to get it working properly.

Either a mac must be borrowed or a virtual machine running osx must be set up to test safari compatibility.
-Safari has been deprecated on windows
-UCR allows people to borrow macbooks so that can be used

**Comment by emmiegit** [comment]
I have access to a MacBook, I'll take a look at this issue.

**Comment by BradleyCai** [comment]
It's too inconvenient to work on @ammongit 's MacBook. I'll go to Watkins' mac lab and debug from there. 

http://www.cnc.ucr.edu/scs/wat2117n.html

**Comment by BradleyCai** [comment]
Turns out the issue lies in bootstrap.
https://github.com/twbs/bootstrap/issues/15935

Popovers that are created using "focus" do not work on safari however the rest still do.
http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_js_popover_trigger&stacked=h

Either a work around must be implemented or we must use "click" to create a popover.
