### ISSUE TITLE
Regex course parsing not working

### ISSUE THREAD

**Issue by BradleyCai** [ammongit/ucr-class-map#50]
https://github.com/BradleyCai/ucr-schedule-visualizer/blob/gh-pages/etc/test_regex_input_4.txt

Produces this

![image](https://cloud.githubusercontent.com/assets/7998948/11021483/1a9124e4-85f7-11e5-9145-75cb1447fb03.png)

Which is incorrect. Something seems to have gone wrong with our regex

**Comment by emmiegit** [comment]
This is tied in with issue #51. Hopefully we'll be able to catch bugs right off the bat before randomly discovering them during development.

**Comment by emmiegit** [comment]
After discussing this bug, we decided that the core issue was how the Javascript used the groups from the regular expressions. Commit 5af2242 fixes this issue, though of the errors mentioned in Bradley's original post, as it is a different issue.
