### ISSUE TITLE
Regexes don't capture certain course times

### ISSUE THREAD

**Issue by BradleyCai** [ammongit/ucr-class-map#55]
Courses with different times for different days are not represented correctly.

For example:
<code>
COE: LEARNING CENTER WORKSHOP<br>
ARC -080 -018     NG    0.00    W   1110AM-1200PM<br>
            M   1110AM-0100PM  
</code>
Produces this:
![image](https://cloud.githubusercontent.com/assets/7998948/11072547/340a0cf6-879b-11e5-9176-66b011121d34.png)

Regex and CourseParser.js should be updated and to fix this issue.

**Comment by emmiegit** [comment]
I think this is an issue with how the JavaScript uses the regular expressions. In my testing, the second regular expression (for 'sessions') caputured a list of all date/times just fine.

**Comment by BradleyCai** [comment]
Fixed in commit 2e51218

![image](https://cloud.githubusercontent.com/assets/7998948/11128983/e723d398-8931-11e5-9b85-c0b8eedb7bc0.png)

It was a problem with the regex. I changed the noncap session regex to be inside of a capture group so it now detects all instances of multiple sessions
