### ISSUE TITLE
does not return back correct information for quarter

### ISSUE THREAD

**Issue by blamejoel** [ammongit/ucr-class-map#60]
Pasted in Winter schedule and Schedule Visualizer generated a schedule with what appeared to be information for the same sections for another quarter.

After further investigation it appears to just not parse all of the course info. For example I see discussions for two of my classes, but the lectures did not transfer over.

**Comment by emmiegit** [comment]
Like you mentioned, it's likely an issue with the parsing. Could you post the input you provided, or if you don't want it visible online, email it to myself or Bradley? Our emails and public keys are available [here](https://bradleycai.github.io/ucr-schedule-visualizer/about.html).

Also, if it's not too difficult, can you provide a screenshot? Thanks.

**Comment by blamejoel** [comment]
It _might_ be related to the building where the courses are located. Both of the courses that don't show up are in a UV THE room. I'll email both of you the schedule input to try out. I was going to try and debug it and let you know exactly where it skips the courses, but I should do my hw first =D.

**Comment by emmiegit** [comment]
Sadly, the school website's list is missing a few, so it might be a building we don't know about. If you replace the building with one that our system does recognize, like `UNLH`, does it work?

**Comment by blamejoel** [comment]
Bingo, that's it. If I change the suspected courses with the same building and room as one of my other classes, they all show up.

**Comment by blamejoel** [comment]
Looks like it's not the building, but the room. It'll take the UV building, but doesn't seem to care for the `THE#` room format. If I just give it a schedule with the `#` instead of the `THE#` that GROWL provides, it works.

**Comment by emmiegit** [comment]
I didn't know GROWL generated room numbers in that format. Send the schedule input and we'll have a fix out for it soon. Thanks for the bug report.

**Comment by blamejoel** [comment]
Yep, apparently for the `UV` Theatre rooms.

**Comment by BradleyCai** [comment]
This bug is now a part of issue #63 and will therefore be closed.
