### ISSUE TITLE
Handling of waitlisted classes

### ISSUE THREAD

**Issue by emmiegit** [ammongit/ucr-class-map#66]
Waitlisted classes are those whose `name` field ends with `" (Waitlisted)"`, and represent classes that the person is not in, but could potentially join later.

How should these classes be displayed? I can think of a few options:
- Display it normally, but make the "(waitlisted)" bold or something
- Display it in a slightly different color
- Show it in the "error" bar

**Comment by BradleyCai** [comment]
With the change to Banner this issue is not relevant.
