### ISSUE TITLE
Display online classes

### ISSUE THREAD

**Issue by emmiegit** [ammongit/ucr-class-map#71]
GROWL lists online classes as those whose building is `"ONLINE"` and room number as `"COURSE"`. Since `"COURSE"` is not a valid room number, the regular expressions should be changed to accept those two values.

**Comment by emmiegit** [comment]
I've created the `issue-71` branch. So far it parses courses properly and makes special popovers, but `CourseParser.js` does not receive online courses. Since @BradleyCai knows this code better than I do, I'm assigning him to it.

**Comment by BradleyCai** [comment]
Implemented changes that fix this issue in commit 3c71f75
