### ISSUE TITLE
Handle course errors better

### ISSUE THREAD

**Issue by BradleyCai** [ammongit/ucr-class-map#76]
Currently when courses don't show the errors are split and a little uninformative:

![image](https://cloud.githubusercontent.com/assets/7998948/13896754/801485a2-ed55-11e5-82c1-d6d35cbca91e.png)

It'd be better to have all the misfit courses that didn't make it on the calendar in one box along with it's own reason for not showing up.

**Comment by emmiegit** [comment]
This will be covered by #85. Closing.
