### ISSUE TITLE
Store schedule in cookie

### ISSUE THREAD

**Issue by BradleyCai** [ammongit/ucr-class-map#79]
It would be nice if a user would only have to input their schedule once, and everytime they visit the site from then on they would see their schedule immediately instead of having to re-enter it.

To do this we could store the user's schedule in a cookie and remember it the next time they visit the website. 

Implementation should use [js-cookie](https://github.com/js-cookie/js-cookie) or any other cookie framework to make things easier and faster to implement.

If we do go through with this feature, we need to be sure to update the [privacy policy](https://bradleycai.github.io/ucr-schedule-visualizer/about.html#privacy) and announce it in our alert box.

**Comment by emmiegit** [comment]
Fixed in #81, closing issue.
